# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "dev.ctf.localhost", primary: true do |box|

    box.vm.box = "ubuntu/xenial64"
    box.vm.network "private_network", ip: '192.168.9.9'

    # sync in source code
    box.vm.synced_folder "./picoCTF", "/sync/picoCTF"
    box.vm.synced_folder "./CTFd", "/CTFd"
    box.vm.synced_folder ".", "/vagrant", disabled: true    # disable default synced folder

    # pre-requisite for ansible
    box.vm.provision "shell", inline: "sudo apt install -y python"

    # install tools
    box.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "./site.yml"
      ansible.inventory_path = "./inventory.yml"
    end

    box.vm.provider "virtualbox" do |vb|
      vb.name = "dev.ctf.localhost"
      vb.cpus = 2
      vb.memory = 4096
      vb.customize [ 'modifyvm', :id, '--uartmode1', 'disconnected'] # fix vagrant import bug
    end
  end

end
